### PR TITLE
Multi dimensional action Issue #19

### PR DESCRIPTION
**Pull request by IamAniket12**
This branch includes code for both Issue 19 and Issue 46.

### CODE REVIEW

**Comment by javiarrobas** [comment]
@IamAniket12 do you think you could add an example and an associated test proving the multi-dimensional action functionality?

**Comment by IamAniket12** [comment]
Sure, will update it soon.

**Comment by IamAniket12** [comment]
Hello @javiarrobas, added a unit test for MultiAction, please review it. Thanks

**Comment by javiarrobas** [comment]
Thanks a lot for the contribution @IamAniket12! I'll review it as soon as possible, hopefully by this week.

**Comment by javiarrobas** [comment]
@IamAniket12 FYI, I've continued your work in this PR: https://github.com/ibpsa/project1-boptest-gym/pull/154. What I've done in summary:
- Moved the functionality of your test to examples (I prefer to have it there so it serves as an example as well). See [here](https://github.com/ibpsa/project1-boptest-gym/blob/c2f16253e3ac1c18e85fb0478308f9b78fb5ce24/examples/run_multiaction.py#L11). 
- Fixed your `_get_indices` method to account for the number of possible actions instead of the number of bins (see [here](https://github.com/ibpsa/project1-boptest-gym/blob/c2f16253e3ac1c18e85fb0478308f9b78fb5ce24/boptestGymEnv.py#L1054). This is the reason why the vectorized environment test was not passing. 
- Added an example to explain functionality. See [here](https://github.com/ibpsa/project1-boptest-gym/blob/c2f16253e3ac1c18e85fb0478308f9b78fb5ce24/boptestGymEnv.py#L1030). 
- Added release notes. See [here](https://github.com/ibpsa/project1-boptest-gym/blob/c2f16253e3ac1c18e85fb0478308f9b78fb5ce24/releasenotes.md?plain=1#L10). 

I'm going to close this already as it is completed by the other PR.

**Pull request merged**
