### PR TITLE
Upgrade requests format due to werkzeug

### PR DESCRIPTION
**Pull request by Learner0x5a**
According to [this](https://stackoverflow.com/questions/72893180/flask-restful-error-request-content-type-was-not-application-json) question, one needs to add the correct location of the input data in requests.

e.g. change 
`requests.put(url, data={'step': self.step_period})`
 to 
`requests.put(url, json={'step': self.step_period})`

Otherwise, flask would raise error: "The browser (or proxy) sent a request that this server could not understand"

### CODE REVIEW

**Comment by dhblum** [comment]
Thanks @Learner0x5a.  This is an update needed for support of using the recently released BOPTEST v0.5.0.  To confirm, you are using v0.5.0?

**Comment by Learner0x5a** [comment]
> Thanks @Learner0x5a. This is an update needed for support of using the recently released BOPTEST v0.5.0. To confirm, you are using v0.5.0?

Yes. I'm using v0.5.0.

**Comment by JavierArroyoBastida** [comment]
@Learner0x5a thank you very much for opening the PR and sorry it took me so long to answer. Since this relates to the update to BOPTEST v0.5.0 that involves some further edits I'm opening a new issue for that [here](https://github.com/ibpsa/project1-boptest-gym/issues/135). I'll let you know once ready.

**Comment by JavierArroyoBastida** [comment]
I'm closing this issue since addressed in https://github.com/ibpsa/project1-boptest-gym/pull/136.

**Comment by JavierArroyoBastida** [comment]
I'm closing this pull request since addressed in https://github.com/ibpsa/project1-boptest-gym/pull/136.

**Pull request closed without merging**
